"""fin_var

Revision ID: 1f1a57fc46ac
Revises: 1ab16e8a213b
Create Date: 2024-03-17 15:24:29.838426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1f1a57fc46ac'
down_revision: Union[str, None] = '1ab16e8a213b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('\n\tОписание:\n\tТаблица "history_requests" представляет собой таблицу в базе данных, которая хранит информацию о запросах пользователей.\n\t\n\tСтруктура:\n\t- Колонка "id" - уникальный идентификатор запроса типа Uuid.\n\t- Колонка "user_id" - идентификатор пользователя (строка), не может быть пустой.\n\t- Колонка "date_request" - дата и время запроса (тип TIMESTAMP), значение по умолчанию - текущая дата и время, не может быть пустой.\n\t- Колонка "vendor_code" - артикул продукта (строка длиной до 50 символов), не может быть пустой.\n\thistory_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('date_request', sa.TIMESTAMP(), nullable=False),
    sa.Column('vendor_code', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('\n\tОписание:\n\tТаблица "products" представляет собой таблицу в базе данных, которая хранит информацию о продуктах.\n\t\n\tСтруктура:\n\t- Колонка "id" - уникальный идентификатор продукта типа Uuid.\n\t- Колонка "name" - название продукта (строка длиной до 100 символов), не может быть пустой.\n\t- Колонка "vendor_code" - артикул продукта (строка длиной до 50 символов), не может быть пустой.\n\t- Колонка "price" - цена продукта (целое число), значение по умолчанию - 0.\n\t- Колонка "rating" - рейтинг продукта (число с плавающей точкой), значение по умолчанию - 0.0.\n\t- Колонка "qty" - количество продукта на складе (целое число), значение по умолчанию - 0.\n\t- Колонка "user_id" - идентификатор пользователя (строка), не может быть пустой.\n\tproducts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('vendor_code', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('history_requests')
    op.drop_table('products')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('vendor_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('qty', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='products_pkey')
    )
    op.create_table('history_requests',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('date_request', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('vendor_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='history_requests_pkey')
    )
    op.drop_table('\n\tОписание:\n\tТаблица "products" представляет собой таблицу в базе данных, которая хранит информацию о продуктах.\n\t\n\tСтруктура:\n\t- Колонка "id" - уникальный идентификатор продукта типа Uuid.\n\t- Колонка "name" - название продукта (строка длиной до 100 символов), не может быть пустой.\n\t- Колонка "vendor_code" - артикул продукта (строка длиной до 50 символов), не может быть пустой.\n\t- Колонка "price" - цена продукта (целое число), значение по умолчанию - 0.\n\t- Колонка "rating" - рейтинг продукта (число с плавающей точкой), значение по умолчанию - 0.0.\n\t- Колонка "qty" - количество продукта на складе (целое число), значение по умолчанию - 0.\n\t- Колонка "user_id" - идентификатор пользователя (строка), не может быть пустой.\n\tproducts')
    op.drop_table('\n\tОписание:\n\tТаблица "history_requests" представляет собой таблицу в базе данных, которая хранит информацию о запросах пользователей.\n\t\n\tСтруктура:\n\t- Колонка "id" - уникальный идентификатор запроса типа Uuid.\n\t- Колонка "user_id" - идентификатор пользователя (строка), не может быть пустой.\n\t- Колонка "date_request" - дата и время запроса (тип TIMESTAMP), значение по умолчанию - текущая дата и время, не может быть пустой.\n\t- Колонка "vendor_code" - артикул продукта (строка длиной до 50 символов), не может быть пустой.\n\thistory_requests')
    # ### end Alembic commands ###
